name: Sync from Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public Repo
      uses: actions/checkout@v3
      with:
        repository: naveedahmed/portfolio
        token: ${{ secrets.PUBLIC_REPO_PAT }}
        ssh-strict: true
        persist-credentials: true
        clean: true
        sparse-checkout-cone-mode: true
        fetch-depth: 1
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Cleanup Old Repo Directory
      run: |
        if [ -d "private-repo" ]; then rm -rf private-repo; fi

    - name: Clone Private Repo
      run: |
        set -e
        git clone --branch live-site https://<token>@github.com/naveedahmed/personal-website.git private-repo
      env:
        PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}

    - name: Verify Clone
      run: |
        if [ -d "private-repo" ]; then echo "Clone successful"; else echo "Clone failed"; fi

    - name: List Files in Private Repo
      run: |
        ls -R private-repo

    - name: Copy Files from Private Repo to Public Repo
      run: |
        git reset --hard
        git clean -fd
        cp -r private-repo/build/* .

    - name: Commit and Push Changes
      run: |
        git config --global user.name "naveedahmed"
        git config --global user.email "ahmed.naveed@yahoo.co.in"
        git add .
        git commit -m "Sync from private repo 'live-site' branch"
        git push https://<token>@github.com/naveedahmed/portfolio.git
      env:
        PUBLIC_REPO_PAT: ${{ secrets.PUBLIC_REPO_PAT }}
