name: Sync Files from Private Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      - name: Cleanup Old Repo Directory
        run: |
          if [ -d "private-repo" ]; then rm -rf private-repo; fi

      - name: Clone Private Repo
        run: |
          set -e
          git clone --branch live-site https://${{ secrets.PRIVATE_REPO_PAT }}@github.com/naveedahmed/personal-website.git private-repo

      - name: List Files in Private Repo
        run: |
          ls -R private-repo

      - name: Reset Public Repo
        run: |
          git reset --hard
          git clean -fd

      - name: Copy Files
        run: |
          cp -r private-repo/build/* .
          git rm -r --cached private-repo

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_PAT }}
        run: |
          git config --global user.name "naveedahmed"
          git config --global user.email "naveedahmedjaleel@gmail.com"
          git add .
          git commit -m "Sync from private repo 'live-site' branch"
          git push https://${{ secrets.PUBLIC_REPO_PAT }}@github.com/naveedahmed/portfolio.git
